export const projects = [
  {
    title: "Loop",
    date: "Oct 2021 - Current",
    body: `Lightweight, SMS-based app for communities to keep in touch long-term.`,
    team: "Silen Naihin, Daniel Garcia",
    programs: "Edyfi, OnDeck Catalyst Hackathon",
    tags: ["NextJS", "TailwindCSS", "Vercel"],
    githubLink: "",
    slidesLink: "",
    otherLink: {
      title: "",
      src: "",
    },
  },
  {
    title: "Corkboard",
    date: "Jul 2021",
    body: `Board for all the pins, files, and browser windows you need for each ongoing workstream, visually organized.`,
    team: "Kelvin Yu, Ivan Zhao, Khushi Selat, Jacky Huang, Vidit Goyal",
    programs: "OnDeck Catalyst Hackathon",
    tags: ["NextJS", "Vercel", "HTML Canvas"],
    githubLink: "https://github.com/danielavelez1201/c-build-weekend",
    slidesLink:
      "https://drive.google.com/file/d/1PhYEacVfP_cKpSeELoDjQ5Ep_IPNGxnc/view?usp=sharing",
    otherLink: {
      title: "Twitter post",
      src: "https://twitter.com/danielarosev/status/1414776059543752707?s=20",
    },
  },
  {
    title: "Techbound",
    date: "Jan-July 2021",
    body: `Mission-driven tech recruiting platform.`,
    team: "Lidia Balanovich, Jordan Lawanson",
    programs: "Womxn Ignite, MIT Sandbox, Dartmouth Tuck-Magnuson Incubator",
    tags: ["React", "MongoDB", "Express", "Node", "Figma"],
    githubLink: "https://github.com/danielavelez1201/techbound",
    slidesLink:
      "https://drive.google.com/file/d/1jRsMGbIVIa2THdCQLRFjSZ9fdH1Dxfrc/view?usp=sharing",
    otherLink: {
      title: "Onepager.vc",
      src: "https://onepager.vc/techbound",
    },
  },
  {
    title: "Findling",
    date: "Aug 2020",
    body: `Educational app that teaches foreign languages to children through an auto-generated scavenger hunt throughout their home.`,
    team: "Aimee Shao, Snow Kang, Waddah Alrobi",
    programs: "Microsoft Intern Hack for Good",
    tags: [
      "Azure object detection",
      "Azure translation",
      "Azure Cosmos DB",
      "Azure App Service",
      "React Native",
    ],
    githubLink: "https://github.com/danielavelez1201/msft-hack",
    slidesLink: "bit.ly/findling-app",
    otherLink: {
      title: "Demo video",
      src: "bit.ly/findling-demo",
    },
  },
  {
    title: "Luma",
    date: "Feb-May 2020",
    body: `App that reveals common local symptoms, conditions, and tips, to empower communities globally.`,
    team: "Shruti Ravikumar",
    programs: "MIT Sandbox",
    tags: ["React Native"],
    githubLink: "https://github.com/danielavelez1201/luma",
    slidesLink:
      "https://drive.google.com/file/d/1M9iO9IS0chAD5ulwliiVSFJI0xXjEQ6K/view?usp=sharing",
    otherLink: {
      title: "Document",
      src: "https://docs.google.com/document/d/11Yrz3c-gRRVYjG46Qq-_zMChuC0sQwFDP-H6AntCd7U/edit",
    },
  },
  {
    title: "JustinCase",
    date: "Sep 2019",
    body: `Website that provides under resourced lawyers with personalized case law information and guidance`,
    team: "Jaidev Shah, Natalia Dorogi, Ryan Sullivan",
    programs: "HackMIT",
    tags: [
      "Google Cloud Servers",
      "AWS chatbot",
      "Python",
      "Bootstrap",
      "HTML/CSS",
    ],
    githubLink: "https://github.com/danielavelez1201/hackmit",
    slidesLink:
      "https://docs.google.com/presentation/d/1mMYRd8uBQZrAK4lPqy5nfoWMDjW3thlJ4yAsNNCTCvQ/edit?usp=sharing",
    otherLink: {
      title: "DevPost",
      src: "https://devpost.com/software/justincase-j16yxu",
    },
  },
  {
    title: "OrgSpace",
    date: "Jul-Aug 2019",
    body: `Social media and networking website for organizations.`,
    team: "Sam Sandoval, TJ Oyeyemi",
    programs: "Google Computer Science Summer Institute (CSSI)",
    tags: [
      "Google Cloud Servers",
      "Python",
      "Bootstrap",
      "HTML/CSS",
      "Google App Engine",
    ],
    githubLink: "https://github.com/danielavelez1201/cssi-orgspace",
    slidesLink: "",
    otherLink: {
      title: "",
      src: "",
    },
  },
  {
    title: "Drum-E",
    date: "Aug 2018 – May 2019",
    body: `Tested different forms of piezoelectricity and developed piezoelectric light-up drums to educate students on clean energy sources.`,
    team: "Amy Haft, Jacob Mass",
    programs: "American Heritage Pre-Engineering Program",
    tags: ["Research"],
    githubLink: "",
    slidesLink: "",
    otherLink: {
      title: "Project report",
      src: "https://drive.google.com/file/d/1WeCSZcYkwtFQV98BdghSOmXskzT-aUAb/view?usp=sharing",
    },
  },
  {
    title: "EasySpin Keyboard",
    date: "Aug 2017 – Apr 2019",
    body: `Florida State Science Fair 6th Place, 
    Wireless keyboard for people with motor disabilities to spin device and press any letter to type.`,
    team: "N/A",
    programs: "American Heritage Pre-Engineering Program",
    tags: ["Arduino", "Autodesk Inventor", "3D printing"],
    githubLink: "",
    slidesLink: "",
    otherLink: {
      title: "Project report",
      src: "https://drive.google.com/file/d/1rFKL12xR6UHwt86pRN3Js1E39sSbLTQ-/view?usp=sharing",
    },
  },
  {
    title: "Water Purification with Polarization of Light Research",
    date: "Sep-Dec 2017",
    body: `Worked weekly with Florida International University to research how to use polarization lens to boil water efficiently with sunlight in a bottle for impoverished areas.`,
    team: "N/A",
    programs: "American Heritage Pre-Engineering Program",
    tags: ["Research"],
    githubLink: "",
    slidesLink: "",
    otherLink: {
      title: "Project report",
      src: "https://drive.google.com/file/d/1lJkrH1Vv0cIsaQJuFMzPy9VxKt2wUQm6/view?usp=sharing",
    },
  },
  {
    title: "Facium",
    date: "June-July 2017",
    body: `Social media website that encourages users to engage in productive group activities by giving users badges and levels in certain activity categories.`,
    team: "Umut Ozturk",
    programs: "Stanford Pre-Collegiate Studies: Web Technologies",
    tags: ["Node", "Express", "Bootstrap", "HTML/CSS"],
    githubLink: "",
    slidesLink: "",
    otherLink: {
      title: "Project report",
      src: "https://drive.google.com/file/d/1lJkrH1Vv0cIsaQJuFMzPy9VxKt2wUQm6/view?usp=sharing",
    },
  },
];
