name: daily-cron
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'http://danielavelez.com/api/send_birthday_reminders'
